### PR TITLE
Use SVT multi cdn selection logic to ensure optimal playback performance

### PR DESCRIPTION
**Pull request by even-stephen**

### CODE REVIEW

**Comment by linqcan** [comment]
Thanks for contributing!
Please provide some background and purpose of this change.

**Comment by even-stephen** [comment]
This change is the equivalent of what the official webplayer (on svtplay.se) is doing when resolving video links, i.e if the alt query is present it will use that as a stream url, otherwise it will use the url "as is"

Ex: useAltHlsUrl variable in:
https://www.svtstatic.se/video/svtvideoplayer/js/svtvideoplayer.js

**Comment by linqcan** [comment]
Sorry for being slow to understand, but why is this needed? What problem or
issue does it resolve?

**Comment by even-stephen** [comment]
SVT is using a multi-CDN approach to serve the content, using the "alturl" (when present) ensures that the best performing CDN get picked for each stream start, allowing for a better user experience.

**Comment by linqcan** [comment]
OK, can you update the commit message to describe this? (the reason behind the change and the benefit of it)

**Comment by even-stephen** [comment]
Ok, updated commit message.

**Comment by linqcan** [comment]
Not really what I meant, but I could have been clearer I suppose. However, it will work.

'Till next time: https://gist.github.com/matthewhudson/1475276

**Pull request merged**
