### PR TITLE
Fix "Latest programs" not showing new items

### PR DESCRIPTION
**Pull request by wader**
Use same api paramaters as svtplay.se

### CODE REVIEW

**Comment by wader** [comment]
I noticed that getItems is used by popular etc also but they seem to work with the new parameters

**Comment by wader** [comment]
Did a quick check and latest program seems to be the only one using `excludedTagsString=lokalt` but currently i can't see any difference with or without it with popular

**Comment by linqcan** [comment]
Thanks for contributing!

Yes, "latest" has a new required parameter (excludedTagsString).

Have to go over tests as they haven't reported any errors for this...

Edit: Removed inaccuracy.

**Comment by linqcan** [comment]
Edit: Nvm, github was lying.

**Comment by wader** [comment]
Ok, thanks! and thank you for this add-on, i'm using a more or less every day 👍

**Comment by linqcan** [comment]
@wader Just tested this, what's the exact issue you are seeing and how does your PR change that?

**Comment by wader** [comment]
@linqcan Without the latest page does include new items for me
Example:
```sh
$ curl -s 'https://www.svtplay.se/api/latest?page=1&excludedTagsString=lokalt&accessServiceFilters=' | jq . | grep -i rapport
      "programTitle": "Rapport",
      "contentUrl": "/video/16016087/rapport/rapport-26-nov-22-30",
      "poster": "https://www.svtstatic.se/image-cms/svtse/1498489833/nyhetsprogrammet-rapport/article14251708.svt/ALTERNATES/{format}/affischbild-rapport-katarina-sandstrom-jpg",
      "thumbnail": "https://www.svtstatic.se/image-cms/svtse/1511732324/nyhetsprogrammet-rapport/se-program/article16119015.svt/ALTERNATES/{format}/default-title",
          "contentUrl": "/video/16016087/rapport/rapport-26-nov-22-30",
$ curl -s 'https://www.svtplay.se/api/latest?page=1' | jq . | grep -i rapport
      "programTitle": "Rapport",
      "contentUrl": "/video/15866827/rapport/rapport-14-nov-19-30-1",
      "poster": "https://www.svtstatic.se/image-cms/svtse/1498489833/nyhetsprogrammet-rapport/article14251708.svt/ALTERNATES/{format}/affischbild-rapport-katarina-sandstrom-jpg",
      "thumbnail": "https://www.svtstatic.se/image-cms/svtse/1510686537/nyhetsprogrammet-rapport/se-program/article15976899.svt/ALTERNATES/{format}/default-title",
          "contentUrl": "/video/15866827/rapport/rapport-14-nov-19-30-1",
mattias@cocospro:~$
```

You see something else?

**Comment by wader** [comment]
Maybe a better example
```sh
$ curl -s 'https://www.svtplay.se/api/latest?page=1&excludedTagsString=lokalt&accessServiceFilters=' | jq .data[].validFrom
"2017-11-26T22:30:00+01:00"
"2017-11-26T21:15:00+01:00"
"2017-11-26T21:00:00+01:00"
"2017-11-26T20:10:00+01:00"
"2017-11-26T20:00:00+01:00"
"2017-11-26T20:00:00+01:00"
"2017-11-26T19:55:00+01:00"
"2017-11-26T19:00:00+01:00"
"2017-11-26T17:55:00+01:00"
"2017-11-26T16:55:00+01:00"
"2017-11-26T16:52:00+01:00"
"2017-11-26T13:00:00+01:00"
"2017-11-26T13:00:00+01:00"
"2017-11-26T12:00:00+01:00"
"2017-11-26T10:05:00+01:00"
"2017-11-26T09:30:00+01:00"
"2017-11-26T06:00:00+01:00"
"2017-11-26T02:00:00+01:00"
"2017-11-26T02:00:00+01:00"
"2017-11-26T02:00:00+01:00"
"2017-11-26T02:00:00+01:00"
"2017-11-26T02:00:00+01:00"
"2017-11-26T02:00:00+01:00"
"2017-11-26T02:00:00+01:00"
"2017-11-26T02:00:00+01:00"
"2017-11-26T02:00:00+01:00"
"2017-11-26T02:00:00+01:00"
"2017-11-26T02:00:00+01:00"
"2017-11-26T02:00:00+01:00"
"2017-11-26T00:01:00+01:00"
"2017-11-25T21:50:00+01:00"
"2017-11-25T21:00:00+01:00"
"2017-11-25T20:10:00+01:00"
"2017-11-25T19:00:00+01:00"
"2017-11-25T18:00:00+01:00"
"2017-11-25T17:50:00+01:00"
"2017-11-25T15:00:00+01:00"
"2017-11-25T10:00:00+01:00"
"2017-11-25T09:00:00+01:00"
"2017-11-25T02:00:00+01:00"
"2017-11-25T02:00:00+01:00"
"2017-11-25T02:00:00+01:00"
"2017-11-25T02:00:00+01:00"
"2017-11-25T02:00:00+01:00"
"2017-11-25T02:00:00+01:00"
"2017-11-25T02:00:00+01:00"
"2017-11-24T21:45:00+01:00"
"2017-11-24T21:18:00+01:00"
$ curl -s 'https://www.svtplay.se/api/latest?page=1' | jq .data[].validFrom
"2017-11-14T21:00:00+01:00"
"2017-11-14T21:00:00+01:00"
"2017-11-14T20:00:00+01:00"
"2017-11-14T19:30:00+01:00"
"2017-11-14T19:00:00+01:00"
"2017-11-14T18:45:00+01:00"
"2017-11-14T18:25:00+01:00"
"2017-11-14T18:13:00+01:00"
"2017-11-14T18:00:00+01:00"
"2017-11-14T18:00:00+01:00"
"2017-11-14T17:45:00+01:00"
"2017-11-14T17:30:00+01:00"
"2017-11-14T17:30:00+01:00"
"2017-11-14T17:30:00+01:00"
"2017-11-14T17:20:00+01:00"
"2017-11-14T17:15:00+01:00"
"2017-11-14T16:00:00+01:00"
"2017-11-14T15:00:00+01:00"
"2017-11-14T12:00:00+01:00"
"2017-11-14T10:15:00+01:00"
"2017-11-14T09:00:00+01:00"
"2017-11-14T06:00:00+01:00"
"2017-11-14T02:00:00+01:00"
"2017-11-14T02:00:00+01:00"
"2017-11-14T02:00:00+01:00"
"2017-11-14T02:00:00+01:00"
"2017-11-14T02:00:00+01:00"
"2017-11-14T02:00:00+01:00"
"2017-11-14T02:00:00+01:00"
"2017-11-14T02:00:00+01:00"
"2017-11-14T02:00:00+01:00"
"2017-11-13T20:00:00+01:00"
"2017-11-13T18:45:00+01:00"
"2017-11-13T02:00:00+01:00"
"2017-11-13T02:00:00+01:00"
"2017-11-13T02:00:00+01:00"
"2017-11-13T02:00:00+01:00"
"2017-11-13T02:00:00+01:00"
"2017-11-13T02:00:00+01:00"
"2017-11-12T21:15:00+01:00"
"2017-11-12T20:10:00+01:00"
"2017-11-12T20:00:00+01:00"
"2017-11-12T19:00:00+01:00"
"2017-11-12T18:30:00+01:00"
"2017-11-12T15:55:00+01:00"
"2017-11-12T15:50:00+01:00"
"2017-11-12T15:30:00+01:00"
"2017-11-12T13:00:00+01:00"
```

**Comment by linqcan** [comment]
@wader thanks for responding.

The reason why I asked is that I first thought the endpoint was requiring a new parameter and not responding when it was missing. Turns out that that was only the behavior in desktop Chrome. When using curl/requests the endpoint still works but gives, as you have discovered, a "randomly" sorted list of some kind. This all seems a bit strange. Will give SVT a day or two before I make an update, incase there is something fishy in their end.

Thanks again for discovering this!
Unfortunately this can't be be catched by the daily tests as they only look for broken endpoints.

**Comment by wader** [comment]
Sounds good and cool that there are daily test running!

**Comment by linqcan** [comment]
Version 4.0.55 has been submitted to Kodi. It can take a day or two for them to push it out (worst case).

**Comment by wader** [comment]
Nice, thanks!

**Pull request merged**
