### PR TITLE
[Review] [Do not merge] Add full parsing of program pages

### PR DESCRIPTION
**Pull request by linqcan**
This commit enables full parsing of program pages so that both episodes and clips are listed
as results. This, however, introduces another level of navigation.

### CODE REVIEW

**Comment by nilzen** [comment]
This should be optional IMO, I don't want the extra navigation level... :)

**Comment by kokangit** [comment]
I have not loooked at the changed code yet. But, would it not be possible to detect the need for extra level and use that just when it is needed?

**Comment by nilzen** [comment]
Still a lot of programs lists programs and clips and I have never watched a single clip.

**Comment by linqcan** [comment]
I have read the discussion and I have some ideas in my head. Though I don't have time to test them this weekend. Expect an updated PR during the upcoming week!

**Comment by linqcan** [comment]
Did a "quick fix" that I had in my head. Maybe the two versions combined and with the option to turn the full parsing off will give a good result?

(Will clean up all strings and replace them with constants before merge.)

**Comment by kokangit** [comment]
Tested in my test environment and it seems to work well. Are there programs that can not been seen? What kind of programs?

**Comment by linqcan** [comment]
All programs can be seen, but clips related to a program will not be accessible from the "browser" if the program has episodes. However, if you search for the show/clip then you will be able to access it (since we divide search results into episodes and clips.

But maybe a version where the user can choose if "episodes" and "clips" will be shown or just "episodes" (and "clips" if there are no "episodes").

**Comment by linqcan** [comment]
Aborting this and will create a new PR since a rebase is needed to be able to test this (site layout has changed).

**Pull request closed without merging**
