### PR TITLE
Do not merge! Site change

### PR DESCRIPTION
**Pull request by linqcan**
Do not merge!
Branch will be squashed when new site goes live!

PR created for reference.

Updated against: http://beta.svtplay.se/

Before going live
- [ ] Change BASE_URL in the svt module
- [ ] Update background image
- [ ] Update README and docs
- [x] Decide if BestOfSvt.se should be included or not ("Populärt" and "Sista chansen" are "native" featues now)
- [x] Create settings module for accessing settings via constants
- [x] Move logic to find video URL to SVT module
- [x] Add images to categories #92 
- [x] Add category "Sändningar"
- [x] Convert SVT date format to XBMC date format for proper "aired" support
- [x] Add unit tests for the SVT module
- [x] Add playlist feature
- [x] Add better support for live broadcasts (only show ongoing?)
- [x] Add support for "Kanaler"

### CODE REVIEW

**Comment by sefsh** [comment]
Thanks for maintaining this addon. :heartbeat:

**Comment by linqcan** [comment]
Pleasure! :smile:

**Comment by linqcan** [comment]
Launch is approaching: http://kundo.se/org/svt-play-beta/d/chromecast-5/#c679102

**Comment by nilzen** [comment]
I guess we should merge this in to master soon then and push it to the add on repo for Gotham, after they launch the new site we can just change the url from beta...

**Comment by linqcan** [comment]
Maybe we should wait until launch, they have changed the naming conventions on some elements back and forth. Guessing this might change until the last minute. Trying to avoid quick fixes due to their last minute change of naming...

Will hopefully be able to clean up the playlist feature and merge/include it into this PR this week.

**Comment by linqcan** [comment]
Added basic playlist support. Adding items from the playlist is done by using the context menu ("c" on a keyboard and "hold menu" on ATV2 (?)). Removing an item from the playlist is done by clicking the context menu button while the item is selected in the mini-gui for the playlist ("playlist manager"). This needs to be added to README and maybe integrate a guide somehow in the plugin.

**Comment by linqcan** [comment]
Preparing for release. Fixing against last-minutes changes from SVT.

**Comment by linqcan** [comment]
Closing this PR. Merge against gotham instead.

**Pull request closed without merging**
