### PR TITLE
Fix crash when adding a favorite for the first time.

### PR DESCRIPTION
**Pull request by T-Svensson**

### CODE REVIEW

**Comment by linqcan** [comment]
what platforms has this been tested on?

**Comment by T-Svensson** [comment]
I've tested this on x86_64 Gentoo GNU/Linux with both Kodi 14.0-rc3 and XBMC 13.0.

**Comment by linqcan** [comment]
Did you see this issue on this platform? Only heard about issues on
raspberry, hence my question.

**Comment by T-Svensson** [comment]
Well, uninstall the addon and then make sure that ~/.xbmc/userdata/addon_data/plugin.video.svtplay/ if you run XBMC, else ~/.kodi/userdata/addon_data/plugin.video.svtplay/ for Kodi is removed before you proceed. Now install the addon again and directly go into the addon and add some random show to the favorites.
According to pacmyc in issue #114, the directory is only created if one enter the settings-menu hence the directory is non-existing if you do like I wrote above.

**Comment by linqcan** [comment]
Finally understand the issue.
Using the "w" flag does not work if the directory where the file is placed does not exist. Assumed that XBMC created the data directory for each plugin, this was not the case in some scenarios.

**Comment by linqcan** [comment]
should fix #114

**Comment by linqcan** [comment]
Thank you for your contribution @T-Svensson !
A pull notification has been sent upstream, this change will hopefully go live in a couple of days.

**Pull request merged**
