### PR TITLE
Fix broken links due to site change on BestOfSvt.se

### PR DESCRIPTION
**Pull request by linqcan**

### CODE REVIEW

**Comment by linqcan** [comment]
Oh, and it is a bit slow since we need to fetch one page for each list item to be able to quick start the video.

**Comment by linqcan** [comment]
Do not merge!

Hold this one; I asked the bestofsvt.se to add an attribute for us to use.

**Comment by nilzen** [comment]
Cant we get him to expose an xml or something else that's easier to parse?

**Comment by linqcan** [comment]
I have asked him to include the SVTPlay URL as data in the anchors on the first page, that way we don't need to traverse each program page.  Will get back when I have got an response.

Example:

```
<a href="/klipp/xxxxx" data-svturl="www.svtplay.se/video/xxxx">innerHTML</a>
```

**Comment by linqcan** [comment]
We got our own "static" page from Ted. It will never change.

Tests showed OK, ready for merge.

**Comment by nilzen** [comment]
Go ahead!

**Comment by linqcan** [comment]
XBMC pull request made for version 3.1.6.

**Pull request merged**
