### PR TITLE
Return episodes in alphabetical order

### PR DESCRIPTION
**Pull request by VioletRed**
Return episodes in alphabetical order. Not sure if it makes sense all the time. Maybe only for A-Ö?

### CODE REVIEW

**Comment by linqcan** [comment]
Hi, thanks for the PR.
However, I am wondering. Why would you like to force sort all program in alphabetical order?
The items are now shown in the chronlogical order given by SVT, your change here to "getProgramItems" would force everyone to get it sorted by title and not by date (as it is on their page).

**Comment by VioletRed** [comment]
> would force everyone to get it sorted by title and not by date (as it is on their page).

They are sort by "date added," but publishing order doesn't match episode order (e.g http://www.svtplay.se/aventyr-i-tid-och-rum). Maybe sort by aired, instead?

**Comment by VioletRed** [comment]
Forget it, "aired" is actually "published," and it's not right. I thought that all programs were called something like "Season Y - episode X," but it seems it's not the case and alphabetic order will mess with some programs. 

I'll think about it because it would be nice that episodes were shown in chronological order (either older first or newer first).

**Comment by linqcan** [comment]
Created a feature branch where I added the option to sort by title using existing XBMC functionality. Enable the option in the add-on settings.
Test it out and leave a comment in this thread. Thanks!

https://github.com/nilzen/xbmc-svtplay/tree/optSort

**Pull request closed without merging**
