### PR TITLE
[Review][Do not merge] Add information about shows and videos

### PR DESCRIPTION
**Pull request by linqcan**
Saw that SVT offered a lot of info in the data tags, why not use it?
This commit adds information such as title, duration and aired date to a list item, which will make the displaying of the list items prettier in many XBMC skins. Though I haven't found any using "aired" yet, maybe it can be omitted?

Known issues:
- SVT gives the duration time as "1h 20 min" but XBMC wants min:sec. This leads to ugly printouts  at times but most of them (videos <60 minutes) looks alright. Can be solved by doing some nifty parsing, but is it worth it?

### CODE REVIEW

**Comment by nilzen** [comment]
I guess a regex can solve it? ((\d+) tim)_( *(\d+) min)_ and multiply the second group, if matched, by 60 and add it to the fourth group?

Haven't tried it myself yet. Don't have much time right now...

**Comment by nilzen** [comment]
`"((\d+) tim)*( *(\d+) min)*( *(\d+) sek)*"`

**Comment by linqcan** [comment]
Was thinking about something like that too. Don't have much time now either...

**Comment by linqcan** [comment]
Well, seems like I got some minutes over. Made a new version which supplies the time in minutes to XBMC since that seems to be the preferred format (why can't they just write that in the documentation?).

Looks pretty decent in both Confluence and Aeon Nox. Press (i) in Confluence to see the plot and runtime. Skins like Aeon Nox has display modes that shows thumbnail, runtime and plot (and they look pretty cool now).

**Comment by nilzen** [comment]
Looks ok to me, go ahead and merge if you don't want to change anything else!

**Comment by linqcan** [comment]
Alright, lets do this!

**Pull request merged**
