### PR TITLE
Add lastest program and latest news broadcast.

### PR DESCRIPTION
**Pull request by linqcan**
Also;
- Add dialog if stream not available through plugin.
- Add instances of variables to prevent if-statements from crashing plugin if url or subtitle is not found.

### CODE REVIEW

**Comment by nilzen** [comment]
I've done some updates so this PR can't be merged, if you fix it I probably can merge tomorrow.

**Comment by linqcan** [comment]
Ok, don't have much time now but will try and rebase as soon as I can.

Btw: Your "live" code is almost identical to the one I have written so far, guess I can scrap that branch now =)
Btw2: Was planning to do the alphabetical thingy for programs (that I never made public for v2), are you also working on that or is that feature "free"? ;)

**Comment by nilzen** [comment]
Not sure what the alphabetical thingy is, so i don't think i'm wirking on it ;)

**Comment by linqcan** [comment]
Sorry, sounded obvious in my head...

It's the division of programs by first character, like the division they have on the "Program" page. In case you don't want to scroll through a lot of programs to reach "Lilyhammer". Was thinking about keeping both options, maybe a toggle in the plugin settings?

**Comment by nilzen** [comment]
Yeah make it optional as a addon setting since I want a long list ;) If you have time, the paging needs to be implemented on programs in categories and videos on programs.

**Comment by linqcan** [comment]
Will try that. Will also look at the paging, when time is given...

**Comment by linqcan** [comment]
You can cancel this pull and I will make a new one when I have rebased

**Pull request closed without merging**
