### PR TITLE
Update for the new SVT Play release

### PR DESCRIPTION
**Pull request by linqcan**

### CODE REVIEW

**Comment by linqcan** [comment]
Merging and going for first release now since the old plugin is dead. This one works according to my tests.
@nilzen

**Comment by nilzen** [comment]
:+1:

**Comment by linqcan** [comment]
Pull request sent to XBMC for the "gotham" branch.

**Comment by sefsh** [comment]
👍

**Comment by linqcan** [comment]
XBMC reported that it has been added to the Gotham repo. Unknown when it goes live, can't see it on the web yet: http://mirrors.xbmc.org/addons/gotham/?C=M;O=D

Repo has been updated though: http://sourceforge.net/p/xbmc/plugins/ci/gotham/tree/

**Comment by linqcan** [comment]
@nilzen can you change the default branch for this repo to "gotham"?

**Pull request merged**
